import canonicalLaneMathlib.AdmissibleClass
import BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean.BrauerGroupDefinition
import BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean.GaloisCohomology
import BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean.AzumayaAlgebras
import BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean.BrauerGroupPackage
import BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean.BrauerGroupClosureRoute
import BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean.BrauerGroupFinalTheorem

namespace HautevilleHouse
namespace BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean

theorem all_brauer_components_imported : True := by
  trivial

end BrauerGroupsAlgebraicAspectsFoundationCanonicalLaneLean
end HautevilleHouse